// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSbGeZ9dSCAwGvO2hhXoJ1U71d5FSIMSo',
    appId: '1:392794439550:web:c98f3f3284b8a1fc28fd2f',
    messagingSenderId: '392794439550',
    projectId: 'employee-form-42fd7',
    authDomain: 'employee-form-42fd7.firebaseapp.com',
    storageBucket: 'employee-form-42fd7.appspot.com',
    measurementId: 'G-PN398VPZ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJVWgVphZnNlJEG3X2KXahDgZNk1P2XG8',
    appId: '1:392794439550:android:c48c58a3ec6d5e7728fd2f',
    messagingSenderId: '392794439550',
    projectId: 'employee-form-42fd7',
    storageBucket: 'employee-form-42fd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAs_cHv5jjwOQCVGIjQiZI84LTsR7Tk1E',
    appId: '1:392794439550:ios:1e431756f905b2a528fd2f',
    messagingSenderId: '392794439550',
    projectId: 'employee-form-42fd7',
    storageBucket: 'employee-form-42fd7.appspot.com',
    iosBundleId: 'com.example.employeeFomr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAs_cHv5jjwOQCVGIjQiZI84LTsR7Tk1E',
    appId: '1:392794439550:ios:1e431756f905b2a528fd2f',
    messagingSenderId: '392794439550',
    projectId: 'employee-form-42fd7',
    storageBucket: 'employee-form-42fd7.appspot.com',
    iosBundleId: 'com.example.employeeFomr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSbGeZ9dSCAwGvO2hhXoJ1U71d5FSIMSo',
    appId: '1:392794439550:web:03fa44e52ab4e19a28fd2f',
    messagingSenderId: '392794439550',
    projectId: 'employee-form-42fd7',
    authDomain: 'employee-form-42fd7.firebaseapp.com',
    storageBucket: 'employee-form-42fd7.appspot.com',
    measurementId: 'G-5FNTCGLM6D',
  );
}
